app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#app/config/routing.yml
main:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
# FOSUserBundle's routing
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sonata_user_profile:
  resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile

# Admin's routing
sonata_user:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /admin

admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin