# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.admin.post:
            class: Application\Sonata\AdminBundle\PostAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
            arguments:
                - ~
                - AppBundle\Entity\Post
                - ~
            calls:
                - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]