services:
    app.admin.post:
        class: Application\Sonata\AdminBundle\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - AppBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [ Application\Sonata\AdminBundle]]